import { beforeAll, afterAll, expect, it } from 'vitest';
import {createDb,makePairedCouple,asUser,asAnon, type Db} from './harness';
let db:Db,a:string,b:string,c:string,outsider:string;
beforeAll(async()=>{db=await createDb();const p=await makePairedCouple(db);a=p.alex;b=p.sam;c=p.coupleId;outsider=(await makePairedCouple(db)).alex;});
afterAll(async()=>db?.close());
async function add(kind='dream',visibility='private') {return (await asUser(db,a,tx=>tx.query<{id:string}>(`insert into shared_dreams(couple_id,owner_id,kind,visibility,payload_ciphertext) values($1,$2,$3,$4,'v1.fake') returning id`,[c,a,kind,visibility]))).rows[0]!.id;}
it('hides private rows from partner, outsiders and anonymous readers',async()=>{const id=await add();for(const uid of [b,outsider])expect((await asUser(db,uid,t=>t.query('select * from shared_dreams where id=$1',[id]))).rows).toHaveLength(0);expect((await asAnon(db,t=>t.query('select * from shared_dreams'))).rows).toHaveLength(0);});
it('shares and unshares only through the owner; partner cannot edit or delete',async()=>{const id=await add();await asUser(db,a,t=>t.query("update shared_dreams set visibility='shared' where id=$1",[id]));expect((await asUser(db,b,t=>t.query('select * from shared_dreams where id=$1',[id]))).rows).toHaveLength(1);expect((await asUser(db,b,t=>t.query("update shared_dreams set payload_ciphertext='v1.changed' where id=$1 returning id",[id]))).rows).toHaveLength(0);expect((await asUser(db,b,t=>t.query('delete from shared_dreams where id=$1 returning id',[id]))).rows).toHaveLength(0);await asUser(db,a,t=>t.query("update shared_dreams set visibility='private' where id=$1",[id]));expect((await asUser(db,b,t=>t.query('select * from shared_dreams where id=$1',[id]))).rows).toHaveLength(0);});
it('refuses plaintext, forged owner, shared anchors and changed row identity',async()=>{await expect(asUser(db,a,t=>t.query("insert into shared_dreams(couple_id,owner_id,kind,visibility,payload_ciphertext) values($1,$2,'dream','private','hello')",[c,a]))).rejects.toThrow();await expect(asUser(db,a,t=>t.query("insert into shared_dreams(couple_id,owner_id,kind,visibility,payload_ciphertext) values($1,$2,'dream','private','v1.fake')",[c,b]))).rejects.toThrow();await expect(add('anchors','shared')).rejects.toThrow();const id=await add();await expect(asUser(db,a,t=>t.query("update shared_dreams set kind='anchors' where id=$1",[id]))).rejects.toThrow();});
it('weekly forecasts are shared but only their author can edit',async()=>{const id=await add('forecast','shared');expect((await asUser(db,b,t=>t.query('select id from shared_dreams where id=$1',[id]))).rows).toHaveLength(1);expect((await asUser(db,b,t=>t.query("update shared_dreams set payload_ciphertext='v1.changed' where id=$1 returning id",[id]))).rows).toHaveLength(0);});
it('roadmaps require both consents and disappear when either leaves',async()=>{await expect(add('roadmap','shared')).rejects.toThrow();await asUser(db,a,t=>t.query('insert into dream_roadmap_consent(couple_id,user_id,enabled) values($1,$2,true)',[c,a]));await expect(add('roadmap','shared')).rejects.toThrow();await expect(asUser(db,a,t=>t.query('insert into dream_roadmap_consent(couple_id,user_id,enabled) values($1,$2,true)',[c,b]))).rejects.toThrow();await asUser(db,b,t=>t.query('insert into dream_roadmap_consent(couple_id,user_id,enabled) values($1,$2,true)',[c,b]));const id=await add('roadmap','shared');await asUser(db,b,t=>t.query('update dream_roadmap_consent set enabled=false where user_id=$1',[b]));for(const uid of [a,b])expect((await asUser(db,uid,t=>t.query('select id from shared_dreams where id=$1',[id]))).rows).toHaveLength(0);});
