"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {useApp} from '@/components/app-provider';
import {Badge,Button,ButtonLink,Card,EmptyState,LoadingBlock,Notice,PageHeader,ProgressBar,SelectField,TextAreaField,TextField,useToast} from '@/components/ui';
import {DrillList,DrillRow} from '@/components/drill-row';
import {useLoad} from '@/lib/ui/hooks';
import {messageOf} from '@/lib/backend/types';
import {EMPTY_ANCHORS,TRACKS,TRACK_COPY,coachSupport,reviewDraft,roadmapProgress,type DreamInput,type DreamKind,type DreamRecord,type DreamPayload,type DreamState} from '@shared/shared-dreams.ts';
export type DreamsView='board'|'roadmap'|'week'|'anchors'|'reflection'|'review';
const ROOT='/plans/dreams/';
const TITLES:Record<DreamsView,string>={board:'Shared Dreams & Support',roadmap:'Our shared roadmap',week:'Our week ahead',anchors:'My Life Anchors',reflection:'My private reflection',review:'Our weekly conversation'};
const KINDS:Record<DreamsView,DreamKind[]>={board:['dream','summary'],roadmap:['roadmap'],week:['forecast','support'],anchors:['anchors'],reflection:['reflection'],review:['appreciation','bid']};
const KIND_TITLE:Record<DreamKind,string>={person:'Person',gathering:'Gathering',health:'Health reminder',dream:'Dream',roadmap:'Roadmap',forecast:'Weekly forecast',support:'Support request',appreciation:'Appreciation',bid:'Connection reflection',anchors:'Life Anchors',reflection:'Private reflection',summary:'Shared summary'};
const today=()=>new Date().toLocaleDateString('en-CA');
const weekStart=()=>{const d=new Date();d.setDate(d.getDate()-d.getDay());return d.toLocaleDateString('en-CA');};
function defaultPayload(kind:DreamKind):DreamPayload {
 switch(kind){
 case 'person':return {name:'',relationship:'',note:''};
 case 'gathering':return {title:'',day:today(),time:'18:00',place:'',note:''};
 case 'health':return {enabled:false,dismissed:false};
 case 'dream':return {title:'',meaning:'',fear:''};
 case 'roadmap':return {title:'',milestones:[{title:'',role:'',done:false}]};
 case 'forecast':return {week:weekStart(),busy:'',moments:['','','']};
 case 'support':return {text:'',options:['A text at lunch','20 minutes of undivided time','An evening with no phones']};
 case 'anchors':return structuredClone(EMPTY_ANCHORS);
 case 'reflection':return {regulation:'',patterns:'',lessons:''};
 case 'appreciation':return {text:'',day:today()};
 case 'bid':return {text:'',day:today(),response:'turned_toward'};
 case 'summary':return {text:''};
 }
}
function Paragraph({label,children}:{label:string;children:string}) {return children?<p className="mt-3 whitespace-pre-wrap break-words text-muted"><strong className="block text-sm text-ink">{label}</strong>{children}</p>:null;}
function CardBody({row}:{row:DreamRecord}) {
 switch(row.kind){
 case 'dream':return <><h3 className="mt-3 text-xl font-bold text-ink">{row.payload.title}</h3><Paragraph label="What it would mean" >{row.payload.meaning}</Paragraph><Paragraph label="What feels uncertain">{row.payload.fear}</Paragraph></>;
 case 'roadmap':return <><h3 className="mt-3 text-xl font-bold">{row.payload.title}</h3><ProgressBar value={roadmapProgress(row.payload.milestones)} max={100} label="Milestones completed"/><ol className="mt-4 space-y-3">{row.payload.milestones.map((m,i)=><li key={i} className="flex gap-3"><span aria-label={m.done?'Done':'Still ahead'}>{m.done?'✓':'○'}</span><span className="break-words"><strong>{m.title}</strong><span className="block text-sm text-muted">{m.role}</span></span></li>)}</ol></>;
 case 'forecast':return <><Paragraph label="Week beginning">{row.payload.week}</Paragraph><Paragraph label="When life is busy">{row.payload.busy}</Paragraph><h3 className="mt-3 font-bold">Protected time together</h3><ul className="mt-2 list-disc space-y-2 pl-5">{row.payload.moments.map((x,i)=><li className="break-words" key={i}>{x}</li>)}</ul></>;
 case 'support':return <><h3 className="mt-3 font-bold">{row.payload.text}</h3><p className="mt-2 text-sm text-muted">Three ways you could help. Talk together about what fits; these are invitations.</p><ul className="mt-3 list-disc space-y-2 pl-5">{row.payload.options.map((x,i)=><li className="break-words" key={i}>{x}</li>)}</ul></>;
 case 'anchors':return <><Paragraph label="My purpose">{row.payload.purpose}</Paragraph><Paragraph label="My routine">{row.payload.routine}</Paragraph><Paragraph label="Skill I’m building">{row.payload.skill}</Paragraph><Paragraph label="Friends and community">{row.payload.community}</Paragraph><Paragraph label="My hobby">{row.payload.hobby}</Paragraph><Paragraph label="Self-reliance I’m practicing">{row.payload.selfReliance.map(x=>({cars_tools:'Cars and tools',cooking:'Cooking',budgeting:'Budgeting',home:'Home basics'})[x]).join(', ')}</Paragraph><p className="mt-3 text-sm">Buddy style: <strong>{TRACK_COPY[row.payload.track]}</strong></p></>;
 case 'reflection':return <><Paragraph label="When emotions rise">{row.payload.regulation}</Paragraph><Paragraph label="Patterns I notice">{row.payload.patterns}</Paragraph><Paragraph label="Lessons I want to carry forward">{row.payload.lessons}</Paragraph></>;
 case 'bid':return <><Paragraph label={row.payload.response==='turned_toward'?'I turned toward connection':row.payload.response==='repair'?'I tried a repair':'A moment I want to revisit'}>{row.payload.text}</Paragraph><p className="mt-2 text-xs text-muted">{row.payload.day} · Only your own actions, no score for your partner.</p></>;
 case 'appreciation':return <><Paragraph label="A little appreciation">{row.payload.text}</Paragraph><p className="mt-2 text-xs text-muted">{row.payload.day}</p></>;
 case 'summary':return <Paragraph label="What I chose to share">{row.payload.text}</Paragraph>;
 }
}

/** Every editor starts private where allowed; sharing is a deliberate, labeled save. */
function DreamEditor({kind,row,onSave,onCancel,pending}:{kind:DreamKind;row?:DreamRecord;onSave:(input:DreamInput)=>Promise<void>;onCancel:()=>void;pending:boolean}) {
 const [payload,setPayload]=useState<DreamPayload>(()=>row?.payload??defaultPayload(kind));
 const [visibility,setVisibility]=useState<'private'|'shared'>(row?.visibility??(['dream','anchors','reflection','bid'].includes(kind)?'private':'shared'));
 const [keepWording,setKeepWording]=useState(false);
 const update=(key:string,value:unknown)=>{setPayload(p=>({...p,[key]:value}) as DreamPayload);setKeepWording(false);};
 const p=payload as unknown as Record<string,unknown>;
 const input=(key:string,label:string,required=false)=><TextAreaField label={label} value={(p[key] as string)??''} onChange={v=>update(key,v)} maxLength={key==='title'||key==='text'&&kind!=='summary'?160:2000} required={required} rows={key==='title'?2:3}/>;
 const combined=JSON.stringify(payload);
 const mirror=reviewDraft(combined);
 const needsMirror=visibility==='shared'&&mirror.needsReflection;
 async function submit(e:FormEvent){e.preventDefault();if(pending||needsMirror&&!keepWording)return;let value=payload;if(kind==='forecast'){const f=payload as DreamPayload<'forecast'>;value={...f,moments:f.moments.map(x=>x.trim()).filter(Boolean)};}await onSave({...(row?{id:row.id}:{}),kind,visibility,payload:value} as DreamInput);}
 return <Card><form onSubmit={submit} className="space-y-5"><h2 className="text-xl font-bold">{row?'Edit':'Add'} {KIND_TITLE[kind].toLowerCase()}</h2><fieldset disabled={pending} className="min-w-0 space-y-5">
 {kind==='dream'&&<>{input('title','My dream',true)}{input('meaning','What it would mean to me')}{input('fear','What I’m afraid of')}<label className="flex min-h-12 items-center gap-3"><input type="checkbox" checked={visibility==='shared'} onChange={e=>setVisibility(e.target.checked?'shared':'private')}/>Share this entire dream card with my partner</label><p className="text-sm text-muted">Sharing includes the dream, meaning, and fears above. Leave this off to keep them private, or write a separate summary.</p></>}
 {kind==='summary'&&<>{input('text','Only the words I want my partner to see',true)}<Notice title="This is a separate shared card. Your private reflections and Life Anchors stay private."/></>}
 {kind==='roadmap'&&<>{input('title','What we’re building together',true)}<p className="text-sm text-muted">Agree on roles together. Only the author edits this roadmap.</p>{(p.milestones as DreamPayload<'roadmap'>['milestones']).map((m,i)=><div key={i} className="space-y-3 rounded-2xl border border-line p-4"><TextField label={`Milestone ${i+1}`} value={m.title} maxLength={160} required onChange={v=>update('milestones',(p.milestones as typeof m[]).map((x,j)=>j===i?{...x,title:v}:x))}/><TextField label={`Role for milestone ${i+1}`} value={m.role} maxLength={160} required onChange={v=>update('milestones',(p.milestones as typeof m[]).map((x,j)=>j===i?{...x,role:v}:x))}/><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={m.done} onChange={e=>update('milestones',(p.milestones as typeof m[]).map((x,j)=>j===i?{...x,done:e.target.checked}:x))}/>Completed</label>{(p.milestones as typeof m[]).length>1&&<Button type="button" variant="ghost" onClick={()=>update('milestones',(p.milestones as typeof m[]).filter((_,j)=>j!==i))}>Remove milestone {i+1}</Button>}</div>)}{(p.milestones as unknown[]).length<12&&<Button type="button" variant="secondary" onClick={()=>update('milestones',[...(p.milestones as unknown[]),{title:'',role:'',done:false}])}>Add another milestone</Button>}</>}
 {kind==='forecast'&&<><TextField label="Week beginning" type="date" required value={p.week as string} onChange={v=>update('week',v)}/>{input('busy','When I’ll be heads-down')}{[0,1,2].map(i=><TextField key={i} label={`Protected moment ${i+1}${i?' (optional)':''}`} required={i===0} maxLength={160} value={(p.moments as string[])[i]??''} onChange={v=>{const a=[...(p.moments as string[])];a[i]=v;update('moments',a);}}/>)}<p className="text-sm text-muted">A two-minute Sunday plan. Only you can edit your forecast; both of you can read it.</p></>}
 {kind==='support'&&<>{input('text','What I need this week',true)}{(p.options as string[]).map((x,i)=><TextField key={i} label={`Support option ${i+1}`} value={x} required maxLength={160} onChange={v=>update('options',(p.options as string[]).map((s,j)=>j===i?v:s))}/>)}</>}
 {kind==='anchors'&&<><Notice title="Only you and your Buddy use these answers.">With Buddy AI on, your Life Anchors are included in your own coaching context. Nothing here is automatically shared with your partner.</Notice><SelectField label="My coaching style" value={p.track as typeof TRACKS[number]} onChange={v=>update('track',v)} options={TRACKS.map(value=>({value,label:TRACK_COPY[value]}))}/><p className="text-sm text-muted">Driven: direction and accountability. Warm: feelings and connection. Balanced: a little of both. You can switch anytime; the same privacy and safety rules apply.</p>{input('purpose','My purpose or mission')}{input('routine','My weekly routine: sleep, movement, work')}{input('skill','One skill I’m building')}{input('community','Friends or community I want to make time for')}{input('hobby','A hobby that matters to me')}<p className="text-sm text-muted">Gaming, making, gardening, anything that’s yours. Spark does not rank or shame hobbies.</p><fieldset><legend className="font-semibold">Self-reliance I’m practicing (optional)</legend>{(['cars_tools','cooking','budgeting','home'] as const).map(k=><label key={k} className="flex min-h-12 items-center gap-3"><input type="checkbox" checked={(p.selfReliance as string[]).includes(k)} onChange={e=>update('selfReliance',e.target.checked?[...(p.selfReliance as string[]),k]:(p.selfReliance as string[]).filter(x=>x!==k))}/>{{cars_tools:'Cars and tools',cooking:'Cooking',budgeting:'Budgeting',home:'Home basics'}[k]}</label>)}</fieldset></>}
 {kind==='reflection'&&<><Notice title="Optional and private. No diagnoses, labels, or relationship predictions."/>{input('regulation','When emotions rise, what helps me pause?')}{input('patterns','When I feel close or distant, what patterns do I notice in myself?')}{input('lessons','What have past relationships taught me?')}<p className="text-sm text-muted">If a pattern is hard to understand or change, a qualified counselor can help you explore it. You don’t need a label to ask for support.</p><Link className="text-accent-text underline" href="/support/">Support resources</Link></>}
 {(kind==='appreciation'||kind==='bid')&&<><TextField label="Day" type="date" value={p.day as string} required onChange={v=>update('day',v)}/>{input('text',kind==='appreciation'?'One thing I appreciated today':'A moment when I could turn toward connection',true)}{kind==='bid'&&<SelectField label="My response" value={p.response as string} onChange={v=>update('response',v)} options={[{value:'turned_toward',label:'I turned toward connection'},{value:'missed',label:'I missed it; I can try again'},{value:'repair',label:'I tried a repair'}]}/>}</>}
 {needsMirror&&<Notice tone="warning" title="A pause before sharing"><p>{mirror.prompt}</p><p className="mt-2">Try: {mirror.reframe}</p><p className="mt-2">This reflects on your draft only; it does not judge your partner.</p><label className="mt-3 flex min-h-11 items-center gap-3"><input type="checkbox" checked={keepWording} onChange={e=>setKeepWording(e.target.checked)}/>I reviewed it and want to keep my wording</label></Notice>}
 <p className="text-sm font-semibold text-muted">{visibility==='private'?'Private: only you can read this.':'Shared: your partner will see exactly the words above.'}</p>
 <div className="flex flex-wrap gap-3"><Button type="submit" disabled={pending||needsMirror&&!keepWording}>{pending?'Saving…':visibility==='shared'?'Save and share':'Save privately'}</Button><Button type="button" variant="ghost" onClick={onCancel}>Cancel</Button></div>
 </fieldset></form></Card>;
}
function WeeklyScript(){return <Card><h2 className="text-xl font-bold">Twenty minutes, together</h2><p className="mt-2 text-muted">Take turns. You can pause or stop whenever you need to.</p><ol className="mt-5 space-y-4">{[['3 min','Appreciation','One thing I appreciated about you this week…'],['4 min','One win each','Something that went well for me…'],['6 min','One ask each','I feel ___. I need ___. Would you be willing to ___?'],['5 min','Our dream update','What moved forward? What needs to change?'],['2 min','Protect one moment','When will we make time for us next week?']].map(([time,title,prompt])=><li key={title}><span className="text-xs font-bold uppercase tracking-wide text-accent-text">{time}</span><h3 className="font-semibold">{title}</h3><p className="text-muted">{prompt}</p></li>)}</ol></Card>;}
export function DreamsScreen({view='board'}:{view?:DreamsView}){const {user}=useApp();return <DreamsContent key={`${user?.id}:${view}`} view={view}/>;}
function DreamsContent({view}:{view:DreamsView}) {
 const {backend,user,nameOf}=useApp();const toast=useToast();const load=useLoad(()=>backend.dreams.list(),[backend,user?.id]);
 const [editor,setEditor]=useState<{kind:DreamKind;row?:DreamRecord}|null>(null);const [busy,setBusy]=useState(false);const lock=useRef(false);const [error,setError]=useState<string|null>(null);const [removing,setRemoving]=useState<string|null>(null);
 // Recheck withdrawn sharing/consent on return; never retain an old list after a failed reload.
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible')void load.reload();};window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};},[load.reload]);
 async function act(fn:()=>Promise<unknown>,done:string){if(lock.current)return;lock.current=true;setBusy(true);setError(null);try{await fn();setEditor(null);setRemoving(null);await load.reload();toast.show(done);}catch(e){setError(messageOf(e));}finally{lock.current=false;setBusy(false);}}
 const header=<PageHeader title={TITLES[view]} subtitle={view==='board'?'Make the future visible. Keep support specific.':undefined} back={{href:view==='board'?'/plans/':ROOT,label:view==='board'?'Plans':'Shared Dreams'}}/>;
 if(load.loading)return <>{header}<LoadingBlock label="Loading your cards…"/></>;
 if(load.error||!load.data)return <>{header}<Notice tone="danger" title={load.error??'Could not load your cards.'}/><Button onClick={()=>void load.reload()}>Try again</Button></>;
 const state:DreamState=load.data;const both=state.roadmapConsent.mine&&state.roadmapConsent.partner;
 const items=state.items.filter(x=>KINDS[view].includes(x.kind));
 const anchor=state.items.find(x=>x.ownerId===user?.id&&x.kind==='anchors');
 const myAnchor=anchor?.kind==='anchors'?anchor.payload:undefined;
 return <>{header}
 {view==='board'&&<><Card className="mb-5 border-accent bg-accent-soft"><p className="text-xs font-bold uppercase tracking-widest text-accent-text">A future worth making room for</p><h2 className="mt-2 text-2xl font-bold text-ink">Your dreams. Our next step.</h2><p className="mt-3 text-muted">Start with what matters to you. Share only when you choose. A busy week makes more sense when you can both see the plan.</p></Card><DrillList label="Shared Dreams tools">{([['roadmap','Our roadmap','Milestones, roles, and progress'],['week','Our week ahead','Busy days, protected time, specific support'],['anchors','My Life Anchors','Purpose, routines, hobbies, and Buddy’s style'],['reflection','My private reflection','Understand my patterns, without labels'],['review','Our weekly conversation','Appreciation and a twenty-minute check-in']] as const).map(([path,title,status])=><li key={path}><DrillRow href={`${ROOT}${path}/`} icon="↗" title={title} status={status}/></li>)}</DrillList><h2 className="mb-3 mt-8 text-xl font-bold">Dream board</h2></>}
 {view==='roadmap'&&<Card className="mb-5"><h2 className="font-bold">Both choose to build together</h2><p className="mt-2 text-muted">Each partner joins separately. Either can leave; shared roadmaps then become hidden and read-only for both until both join again.</p><p className="my-3 text-sm">You: {state.roadmapConsent.mine?'joined':'not joined'} · Your partner: {state.roadmapConsent.partner?'joined':'not joined'}</p><Button disabled={busy} variant={state.roadmapConsent.mine?'secondary':'primary'} onClick={()=>void act(()=>backend.dreams.consent(!state.roadmapConsent.mine),state.roadmapConsent.mine?'You left the roadmap.':'You joined the roadmap.')}>{state.roadmapConsent.mine?'Leave the shared roadmap':'Join the shared roadmap'}</Button></Card>}
 {view==='review'&&<><WeeklyScript/><Card className="my-5"><h2 className="font-bold">Small moments count</h2><p className="mt-2 text-muted">What did you appreciate today? When did you respond to an invitation for connection? Reflect on your own actions privately. No streaks, partner scores, or relationship grades.</p><p className="mt-3 text-sm">Your saved reflections: {items.filter(x=>x.kind==='bid'&&x.payload.response==='turned_toward').length} turned toward connection · {items.filter(x=>x.kind==='bid'&&x.payload.response==='repair').length} repairs tried. These are only the moments you recorded.</p></Card></>}
 {view==='anchors'&&<Card className="mb-5"><h2 className="font-bold">A life that’s yours, too</h2><p className="mt-2 text-muted">Optional prompts for your direction, routines, skills, and people. Choose a coaching style now or change it whenever you want.</p><p className="mt-3 text-ink">{coachSupport('Help with my weekly routine',myAnchor?.track,myAnchor).text}</p><ButtonLink href="/us/buddy/" variant="secondary">Talk with Buddy</ButtonLink></Card>}
 {error&&<Notice tone="danger" title={error} className="my-4"/>}
 {editor?<div className="my-5"><DreamEditor key={editor.row?.id??editor.kind} {...editor} pending={busy} onCancel={()=>setEditor(null)} onSave={input=>act(()=>backend.dreams.save(input),input.visibility==='shared'?'Shared card saved.':'Saved privately.')}/></div>:<div className="my-5 flex flex-wrap gap-3">{KINDS[view].filter(k=>!['anchors','reflection'].includes(k)||!items.some(x=>x.kind===k&&x.ownerId===user?.id)).map(kind=><Button key={kind} disabled={busy||kind==='roadmap'&&!both} variant={kind==='summary'||kind==='bid'?'secondary':'primary'} onClick={()=>setEditor({kind})}>{kind==='summary'?'Share a summary':`Add ${KIND_TITLE[kind].toLowerCase()}`}</Button>)}</div>}
 {!items.length&&!editor&&<EmptyState emoji="○" title={view==='roadmap'&&!both?'Waiting for both partners':'Room for your first card'} body={view==='roadmap'&&!both?'There is no deadline to join. Both people get a choice.':'Start small. You can edit or remove your own cards anytime.'}/>}
 <div className="space-y-4">{items.map(row=><Card key={row.id} as="article"><div className="flex flex-wrap items-center justify-between gap-2"><Badge tone={row.visibility==='private'?'muted':'accent'}>{row.visibility==='private'?'Only you':'Shared'}</Badge><span className="text-sm text-muted">{nameOf(row.ownerId)} · {KIND_TITLE[row.kind]}</span></div><CardBody row={row}/>{row.ownerId===user?.id&&<div className="mt-5 border-t border-line pt-3">{removing===row.id?<><p className="mb-2 text-sm">Remove this card? This cannot be undone.</p><Button disabled={busy} variant="secondary" onClick={()=>void act(()=>backend.dreams.remove(row.id),'Card removed.')}>Remove card</Button><Button variant="ghost" onClick={()=>setRemoving(null)}>Keep it</Button></>:<div className="flex flex-wrap gap-2"><Button disabled={busy} variant="ghost" onClick={()=>{setError(null);setEditor({kind:row.kind,row});window.scrollTo({top:0,behavior:'instant'});}}>Edit {KIND_TITLE[row.kind].toLowerCase()}</Button>{row.kind==='dream'&&row.visibility==='shared'&&<Button disabled={busy} variant="ghost" onClick={()=>void act(()=>backend.dreams.save({id:row.id,kind:'dream',visibility:'private',payload:row.payload}),'Dream is private again.')}>Stop sharing</Button>}<Button disabled={busy} variant="ghost" onClick={()=>setRemoving(row.id)}>Remove</Button></div>}</div>}</Card>)}</div>
 <p className="mt-6 text-sm text-muted">{backend.mode==='demo'?'Demo: fictional partners; data stays in this browser.':'Private cards are encrypted and available only to their author.'} Spark supports reflection, not diagnosis or predictions.</p>
 </>;
}
