"use client";

import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { useApp } from "@/components/app-provider";
import { CrisisResources } from "@/components/crisis-resources";
import { Button, Card, Notice, PageHeader, TextAreaField, useToast } from "@/components/ui";
import { useAction, useLoad } from "@/lib/ui/hooks";
import { periodOf, formatPeriod } from "@/lib/domain/dates";
import { CHECKIN_QUESTIONS, type CheckinAnswers } from "@shared/checkin-questions.ts";
import { answersMentionCrisis } from "@shared/checkin-summary.ts";

const blank = (): CheckinAnswers => ({ best: "", closest: "", distant: "", more_of: "", talk_about: "" });

export function MonthlyScreen() {
  const params = useSearchParams();
  const { backend, user, partner } = useApp();
  const toast = useToast();
  const periodParam = params.get("period");
  const period = periodParam && /^\d{4}-(0[1-9]|1[0-2])$/.test(periodParam) ? periodParam : periodOf(new Date());
  const view = useLoad(() => backend.checkins.get(period), [backend, user?.id, period]);
  const [answers, setAnswers] = useState<CheckinAnswers>(blank);
  const [saved, setSaved] = useState(false);
  useEffect(() => { if (view.data?.mine) { setAnswers(view.data.mine); setSaved(view.data.iSubmitted); } }, [view.data]);
  const submit = useAction(async () => {
    const result = await backend.checkins.submit(period, answers);
    setSaved(true);
    await view.reload();
    return result;
  });
  const partnerName = partner?.nickname || partner?.displayName || "your partner";
  const crisis = answersMentionCrisis(answers) || Boolean(view.data?.summary?.safetyFlag);

  return (
    <>
      <PageHeader title={formatPeriod(period)} subtitle="Monthly check-in" back={{ href: "/checkin/", label: "Check-in" }} />
      <Card>
        <h2 className="text-xl font-bold text-ink">Five private questions</h2>
        <p className="mt-1 text-sm leading-relaxed text-muted">Your answers stay hidden from {partnerName} until you have both submitted. Answer what feels useful and leave anything blank.</p>
        <div className="mt-5 space-y-1">
          {CHECKIN_QUESTIONS.map((q) => <TextAreaField key={q.id} label={q.prompt} hint={q.placeholder} value={answers[q.id]} onChange={(value) => setAnswers((old) => ({ ...old, [q.id]: value }))} maxLength={1000} rows={3} disabled={saved} />)}
        </div>
        {!saved ? <Button loading={submit.pending} onClick={async () => { const result = await submit.run(); if (result) toast.show(`Saved privately. ${partnerName} cannot see it yet.`); }}>Submit privately</Button> : <Notice tone="success" title={view.data?.revealed ? "You are both in." : `Hidden until ${partnerName} answers.`}>Your answers are saved privately.</Notice>}
        {submit.error ? <Notice tone="danger" className="mt-3" title={submit.error} /> : null}
      </Card>
      {view.data?.revealed && view.data.partner && view.data.mine ? <>
        <section aria-labelledby="answers-title" className="mt-6">
          <h2 id="answers-title" className="text-xl font-bold text-ink">Read together</h2>
          <div className="mt-3 space-y-3">{CHECKIN_QUESTIONS.map((q) => <Card key={q.id}><h3 className="font-semibold text-ink">{q.prompt}</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-surface-2 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted">You</p><p className="mt-1 whitespace-pre-wrap text-ink">{view.data!.mine![q.id] || "No answer"}</p></div><div className="rounded-2xl bg-accent-soft p-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted">{partnerName}</p><p className="mt-1 whitespace-pre-wrap text-ink">{view.data!.partner![q.id] || "No answer"}</p></div></div></Card>)}</div>
        </section>
        {view.data.summary ? <Card className="mt-6" aria-labelledby="summary-title"><h2 id="summary-title" className="text-xl font-bold text-ink">A shared reflection</h2><p className="mt-1 text-sm text-muted">{view.data.summary.source === "fallback" ? "A simple reflection from Spark's built-in summary." : "A reflection generated by Claude from the answers you both submitted."}</p><h3 className="mt-4 font-semibold text-ink">What overlaps</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-ink">{view.data.summary.overlaps.map((item) => <li key={item}>{item}</li>)}</ul>{view.data.summary.gaps.length ? <><h3 className="mt-4 font-semibold text-ink">What is worth noticing</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-ink">{view.data.summary.gaps.map((item) => <li key={item}>{item}</li>)}</ul></> : null}<h3 className="mt-4 font-semibold text-ink">A question to carry forward</h3><p className="mt-1 text-ink">{view.data.summary.conversationStarter}</p></Card> : null}
      </> : null}
      {crisis ? <CrisisResources urgent className="mt-6" /> : null}
    </>
  );
}
