'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useApp} from '@/components/app-provider';
import {Button,Card,PageHeader,Notice,ChoiceGroup,TextField,TextAreaField,Badge} from '@/components/ui';
import {ASK_FIRST,MENU_NOTE,EMPTY_MENU,INTIMACY_CATALOG,SAFETY_COPY,LEARN_LINKS,allowedEducationLink,type Choice,type IntimacyCard,type IntimacyNote,type IntimacyAction} from '@shared/intimacy.ts';
import {useIntimacy} from './use-intimacy';
import {IntimacySettings} from './intimacy-settings';
import {LineDrawing,GuideAvatar} from './line-drawing';
type View='menu'|'comfort'|'library'|'coach'|'reflection';
const views:Array<[View,string,string]>=[['menu','Our Menu','/intimacy/'],['comfort','Comfort map','/intimacy/comfort/'],['library','Idea library','/intimacy/library/'],['coach','Your guide','/intimacy/coach/'],['reflection','Afterwards','/intimacy/reflection/']];
function Safety({done,close}:{done():void;close():void}){return <Card className="my-4"><PageHeader title="Safety comes first" subtitle="Read this each time before opening play basics."/>{SAFETY_COPY.map(s=><p className="my-3 text-sm" key={s}>{s}</p>)}<div className="flex flex-wrap gap-2"><Button onClick={done}>I’ve read this · Continue</Button><Button variant="ghost" onClick={close}>Back to library</Button></div></Card>;}
function Details({card,close}:{card:IntimacyCard;close():void}){return <Card className="my-4"><LineDrawing kind={card.diagram} title={card.title}/><h2 className="mt-4 text-xl font-bold">{card.title}</h2><p className="my-3">{card.description}</p><h3 className="font-bold">Comfort & mobility</h3><p className="mb-3 text-sm text-muted">{card.comfort}</p><h3 className="font-bold">Pacing</h3><p className="mb-3 text-sm text-muted">{card.pace}</p><p className="font-bold text-accent-text">{ASK_FIRST}</p><div className="my-4 space-y-2">{LEARN_LINKS.filter(l=>allowedEducationLink(l.url)).map(l=><a key={l.url} href={l.url} target="_blank" rel="noopener noreferrer" className="block text-sm underline">Learn more: {l.label} ↗</a>)}</div><Button variant="secondary" onClick={close}>Back to library</Button></Card>;}
function PrivateCoach(){const {backend,user}=useApp();const [note,setNote]=useState<IntimacyNote|null>(null);const [text,setText]=useState('');const [ai,setAi]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [source,setSource]=useState('');useEffect(()=>{let live=true;setNote(null);backend.intimacy.note().then(n=>{if(live)setNote(n);}).catch(()=>{if(live)setError('Could not load your private conversation.');});return()=>{live=false;};},[backend,user?.id]);
 async function send(message:string){if(busy||!message.trim())return;setBusy(true);setError('');try{const r=await backend.intimacy.coach(message,ai);setSource(r.source==='claude'?'AI selected a guide response':'Built-in guide');setNote(await backend.intimacy.note());setText('');}catch(e){setError(e instanceof Error?e.message:'Could not reply.');}finally{setBusy(false);}}
 return <><Card><div className="flex gap-3"><GuideAvatar/><div><h2 className="text-xl font-bold">Your Intimacy guide</h2><p className="text-sm text-muted">A private, non-explicit conversation guide. I can help you ask clearly, build anticipation and listen. I cannot know what your partner wants.</p></div></div><div className="mt-4 flex flex-wrap gap-2">{['Build anticipation','Help us out of a rut','Different levels of desire','What is the next move?'].map(p=><Button disabled={busy} variant="secondary" key={p} onClick={()=>void send(p)}>{p}</Button>)}</div></Card><div role="log" aria-label="Private guide conversation" className="my-4 space-y-3">{note?.history.map((m,i)=><Card key={i} className={m.role==='user'?'ml-8':'mr-4'}><p className="mb-1 text-xs font-bold text-muted">{m.role==='user'?'You':'Intimacy guide'}</p><p>{m.content}</p></Card>)}</div>{error&&<Notice tone="danger" title={error}/>}<form onSubmit={e=>{e.preventDefault();void send(text);}}><TextAreaField label="Ask your guide" value={text} onChange={setText} maxLength={1000}/>{backend.mode==='live'&&<label className="my-3 flex items-start gap-2 text-sm"><input type="checkbox" checked={ai} onChange={e=>setAi(e.target.checked)}/>Use AI to choose guidance using my message, recent private conversation, own map and shared overlaps. Otherwise use the built-in guide.</label>}<Button type="submit" className="mt-3" loading={busy} disabled={!note||!text.trim()}>Ask guide</Button><p role="status" className="mt-2 text-xs text-muted">{source}</p></form></>;}
function Reflection(){
 const {backend,user}=useApp();
 const [repeat,setRepeat]=useState(''),[change,setChange]=useState(''),[share,setShare]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 useEffect(()=>{let live=true;backend.intimacy.note().then(n=>{if(live){setRepeat(n.repeat);setChange(n.change);setLoaded(true);}}).catch(()=>{if(live)setStatus('Could not load your reflection. Reopen this page to retry.');});return()=>{live=false;};},[backend,user?.id]);
 return <Card><h2 className="text-xl font-bold">What felt good for you?</h2><p className="my-3 text-sm text-muted">Each person reflects privately. This form shares nothing automatically.</p>
 <TextAreaField label="One thing to repeat" value={repeat} onChange={setRepeat} maxLength={1000}/><TextAreaField label="One thing to change" value={change} onChange={setChange} maxLength={1000}/>
 <Button className="mt-3" loading={busy} disabled={!loaded} onClick={async()=>{setBusy(true);try{await backend.intimacy.saveNote({repeat,change});setStatus('Saved for you only.');}catch(e){setStatus(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}}>Save private reflection</Button>
 <div className="mt-6 border-t border-line pt-4"><h3 className="font-bold">Share only what you choose</h3><p className="my-2 text-sm text-muted">Write a separate message below. Copy it to share yourself, or say it in person. Your private notes above stay here.</p><TextAreaField label="Only the words I want to share (optional)" value={share} onChange={setShare} maxLength={1000}/><Button variant="secondary" disabled={!share.trim()} onClick={async()=>{try{await navigator.clipboard.writeText(share);setStatus('Copied only your chosen words. Nothing was sent.');}catch{setStatus('Copy is unavailable. Select your chosen words and copy them manually.');}}}>Copy chosen words</Button></div>
 <p role="status" className="mt-3 text-sm">{status}</p></Card>;
}
function IntimacyBody({view='menu'}:{view?:View}){const {user,backend,nameOf}=useApp();const {data,error,pending,act}=useIntimacy();const [selected,setSelected]=useState<string|null>(null);const [safe,setSafe]=useState(false);const [timeItem,setTimeItem]=useState<string|null>(null);const [when,setWhen]=useState('');const [label,setLabel]=useState('Tonight');const [safetyAction,setSafetyAction]=useState<IntimacyAction|null>(null);
 const sharedAction=(c:IntimacyCard,input:IntimacyAction)=>{if(c.safety)setSafetyAction(input);else void act(input);};
 const card=INTIMACY_CATALOG.find(c=>c.id===selected);const close=()=>{const previous=selected;setSelected(null);setSafe(false);requestAnimationFrame(()=>document.getElementById('idea-'+previous)?.focus());};
 useEffect(()=>{if(selected){const el=document.getElementById('intimacy-detail');el?.focus();el?.scrollIntoView?.({block:'start'});}},[selected,safe]);
 if(!data)return <><PageHeader title="Intimacy"/>{error?<Notice tone="danger" title={error}/>:<p>Loading your private area…</p>}</>;
 if(!data.enabled)return <><PageHeader title="Intimacy" subtitle="Your choice, at your pace."/><IntimacySettings key={user?.id}/></>;
 const weekly=data.overlaps.length?INTIMACY_CATALOG.find(c=>c.id===data.overlaps[Math.floor(Date.now()/604800000)%data.overlaps.length]):null;
 return <><PageHeader title="Intimacy" subtitle="Something to look forward to. Room to choose, every time." action={<Link className="font-semibold underline" href="/us/settings/">Settings</Link>}/>{backend.mode==='demo'&&<Notice title="Demo · fictional Alex and Sam" className="mb-4">Explore by switching people. These are browser-only examples; use no real private information here.</Notice>}<nav aria-label="Intimacy sections" className="mb-5 flex flex-wrap gap-2">{views.map(([v,title,url])=><Link key={v} href={url} aria-current={v===view?'page':undefined} className={`rounded-full border px-4 py-3 text-sm font-semibold ${v===view?'bg-accent text-accent-ink':'border-line bg-surface'}`}>{title}</Link>)}</nav>{error&&<Notice tone="danger" className="mb-4" title={error}/>}
 {safetyAction&&<Safety done={()=>{void act(safetyAction);setSafetyAction(null);}} close={()=>setSafetyAction(null)}/>}
 {view==='comfort'&&<><Notice title="Your map is private" className="mb-4">Only mutual Yes or Maybe items appear together. No, Not now and unanswered items look the same to your partner. New openness after an edit starts the next day (UTC); No and Not now take effect immediately.</Notice><div className="space-y-4">{INTIMACY_CATALOG.map(c=>{const answer=data.answers[c.id];return <Card key={c.id}><Badge>{c.category}</Badge><h2 className="my-3 font-bold">{c.title}</h2><ChoiceGroup legend={`Your comfort with ${c.title}`} name={c.id} value={answer?.pending??answer?.choice??''} onChange={choice=>{if(!pending)void act({action:'answer',item:c.id,choice:choice as Choice});}} options={[{value:'yes',label:'Yes'},{value:'maybe',label:'Maybe'},{value:'not_now',label:'Not now'},{value:'no',label:'No'}]}/>{answer?.pending&&<p className="mt-2 text-xs text-muted">Your update starts {new Date(answer.effectiveAt!).toLocaleString()}.</p>}</Card>;})}</div></>}
 {view==='library'&&(card?<div id="intimacy-detail" tabIndex={-1}>{card.safety&&!safe?<Safety done={()=>setSafe(true)} close={close}/>:<Details card={card} close={close}/>}</div>:<><Notice title="A library for connection" className="mb-4">Neutral line drawings and plain guidance. Browsing is private and is never an invitation. Ideas are not medical advice.</Notice><div className="grid gap-4 sm:grid-cols-2">{INTIMACY_CATALOG.map(c=><Card key={c.id}><LineDrawing kind={c.diagram} title={c.title}/><p className="mt-3 text-xs text-muted">{c.category}</p><h2 className="my-2 text-lg font-bold">{c.title}</h2><Button id={'idea-'+c.id} variant="secondary" onClick={()=>{setSelected(c.id);setSafe(false);}}>{c.safety?'Read safety & basics':'Explore idea'}</Button></Card>)}</div></>)}
 {view==='coach'&&<PrivateCoach key={user?.id}/>}{view==='reflection'&&<Reflection key={user?.id}/>}
 {view==='menu'&&!safetyAction&&<><Card className="mb-4"><div className="flex gap-3"><GuideAvatar/><div><h2 className="text-xl font-bold">Our Menu</h2><p className="mt-2 text-sm">{MENU_NOTE}</p><p className="mt-2 text-sm text-muted">Being open to a lot is not a yes to everything, every time. A caring next move starts with a question.</p></div></div><Link className="mt-4 inline-block font-semibold underline" href="/intimacy/coach/">Plan a little anticipation with your guide →</Link></Card>
 {weekly&&<Card className="mb-4"><Badge>This week · one small change</Badge><h2 className="mt-2 font-bold">{weekly.title}</h2><p className="mt-2 text-sm">An option from your current overlaps. You can pass, or ask whether it sounds good this week.</p><p className="mt-2 text-sm font-bold">{ASK_FIRST}</p></Card>}
 <p className="mb-4 text-sm text-muted">Tap up to three private sparks. They last 24 hours. Only a mutual spark lights up for both of you.</p>{!data.overlaps.length&&<Notice title="Room to choose">{EMPTY_MENU} <Link href="/intimacy/comfort/" className="underline">Open your comfort map.</Link></Notice>}
 <div className="grid gap-4 sm:grid-cols-2">{INTIMACY_CATALOG.filter(c=>data.overlaps.includes(c.id)).map(c=><Card key={c.id}><LineDrawing kind={c.diagram} title={c.title}/><h2 className="my-3 text-lg font-bold">{c.title}</h2>{data.matched.includes(c.id)&&<Badge>You both want this</Badge>}<p className="my-3 text-sm font-semibold text-accent-text">{ASK_FIRST}</p><div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={pending} onClick={()=>void act({action:'spark',item:c.id})}>{data.sparks.includes(c.id)?'♥ Your private spark':'♡ Spark privately'}</Button><Button variant="ghost" disabled={pending} onClick={()=>sharedAction(c,{action:'propose',item:c.id,kind:'invite'})}>Invite to discuss</Button>{data.matched.includes(c.id)&&<Button disabled={pending} onClick={()=>setTimeItem(c.id)}>Propose a time</Button>}</div></Card>)}</div>
 {timeItem&&<Card className="my-4"><h2 className="font-bold">A time for {INTIMACY_CATALOG.find(c=>c.id===timeItem)?.title}</h2><ChoiceGroup legend="Invitation wording" name="time-label" value={label} onChange={setLabel} options={['Tonight','This weekend','Surprise me'].map(v=>({value:v,label:v}))}/><TextField label="Date & time" type="datetime-local" value={when} onChange={setWhen}/><p className="my-3 text-sm">Even a surprise needs an agreed time and boundaries. {ASK_FIRST}</p><Button disabled={pending||!when} onClick={async()=>{sharedAction(INTIMACY_CATALOG.find(c=>c.id===timeItem)!,{action:'propose',kind:'time',item:timeItem,when:new Date(when).toISOString(),label});setTimeItem(null);}}>Propose</Button><Button variant="ghost" onClick={()=>setTimeItem(null)}>Cancel</Button></Card>}
 <div className="my-5 space-y-3">{data.invitations.map(i=><Card key={i.id}><h2 className="font-bold">{nameOf(i.ownerId)} would like to explore {INTIMACY_CATALOG.find(c=>c.id===i.item)?.title.toLowerCase()}</h2><p className="my-2 text-sm font-semibold">{ASK_FIRST}</p>{i.when&&<p className="my-2">{i.label} · {new Date(i.when).toLocaleString()}</p>}{i.status==='pending'?(i.ownerId!==user?.id?<div className="flex flex-wrap gap-2">{(i.kind==='invite'?[['yes','Yes'],['later','Maybe later'],['no','Not this time']]:[['yes','Yes'],['not_tonight','Not tonight'],['another_time','Another time']]).map(([value,title])=><Button key={value} variant="secondary" disabled={pending} onClick={()=>void act({action:'respond',id:i.id,response:value as 'yes'})}>{title}</Button>)}</div>:<p className="text-sm text-muted">Invitation left open. No follow-up is needed.</p>):i.status==='another_time'?<p>Another time. There is nothing to explain.</p>:<><p className="text-sm">Welcome to ask. Agreement is not obligation.</p>{i.kind==='time'&&<>{!data.muted&&i.when&&Date.parse(i.when)>Date.now()&&<p className="my-3">Something to look forward to in about {Math.max(1,Math.ceil((Date.parse(i.when)-Date.now())/3600000))} hours. “Looking forward to time together — we can choose how it feels when we get there.”</p>}{i.when&&Date.now()>=Date.parse(i.when)-3600000&&Date.now()<=Date.parse(i.when)+14400000&&<div className="mt-3"><h3 className="font-bold">Still feeling it?</h3><p className="my-2 text-sm">Only two current yes answers show a shared ready signal. Either person can step back.</p><Button disabled={pending} variant="secondary" onClick={()=>void act({action:'check',id:i.id,feeling:true})}>Yes, right now</Button><Button disabled={pending} variant="ghost" onClick={()=>void act({action:'check',id:i.id,feeling:false})}>Step back</Button><p className="mt-2 text-sm">{i.ready?'Both checked in. Ask again as you go.':'Take a moment together. No shared ready signal.'}</p></div>}</>}</>}</Card>)}</div>
 <Card><h2 className="font-bold">Only for you</h2><label className="my-3 flex gap-3"><input type="checkbox" checked={!data.muted} onChange={e=>void act({action:'preferences',muted:!e.target.checked})}/>Show gentle anticipation prompts on this screen</label><p className="mb-3 text-xs text-muted">Off by default. Nothing is sent. Muting is private.</p><ChoiceGroup legend="Your desire today (private)" name="desire" value={data.desire?.toString()??''} onChange={v=>void act({action:'preferences',desire:Number(v)})} options={[1,2,3,4,5].map(n=>({value:String(n),label:n===1?'1 · Low':n===5?'5 · High':String(n)}))}/></Card></>}
 </>;
}

export function IntimacyScreen({view='menu'}:{view?:View}){const {user}=useApp();return <IntimacyBody key={user?.id} view={view}/>;}
