'use client';
import Link from 'next/link';
import {useState} from 'react';
import {useApp} from '@/components/app-provider';
import {Button,Card,PageHeader,Notice,TextField,TextAreaField,ChoiceGroup} from '@/components/ui';
import {useLoad} from '@/lib/ui/hooks';
import {icsEscape,icsFold} from '@/lib/domain/date-rules';
import type {DreamRecord} from '@shared/shared-dreams.ts';
function calendar(row:Extract<DreamRecord,{kind:'gathering'}>){const p=row.payload;const stamp=p.day.replaceAll('-','')+'T'+p.time.replace(':','')+'00';const body=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Spark//Gatherings//EN','BEGIN:VEVENT','UID:'+row.id+'@spark','DTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''),'DTSTART:'+stamp,'DURATION:PT1H','SUMMARY:'+icsEscape(p.title),'LOCATION:'+icsEscape(p.place),'DESCRIPTION:'+icsEscape(p.note),'END:VEVENT','END:VCALENDAR'].map(icsFold).join('\r\n')+'\r\n';const url=URL.createObjectURL(new Blob([body],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='spark-gathering.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function PeopleScreen(){const {backend,user}=useApp();const list=useLoad(async()=>{const [cards,story]=await Promise.all([backend.dreams.list(),backend.story.list()]);return {cards:cards.items,story};},[backend,user?.id]);const [form,setForm]=useState<'person'|'gathering'|'moment'|null>(null);const [title,setTitle]=useState(''),[relation,setRelation]=useState('Family'),[day,setDay]=useState(''),[time,setTime]=useState('18:00'),[place,setPlace]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const [editId,setEditId]=useState<string|undefined>();
 const people=list.data?.cards.filter((c):c is Extract<DreamRecord,{kind:'person'}>=>c.kind==='person')??[];const gatherings=(list.data?.cards.filter((c):c is Extract<DreamRecord,{kind:'gathering'}>=>c.kind==='gathering')??[]).sort((a,b)=>a.payload.day.localeCompare(b.payload.day));const health=list.data?.cards.find((c):c is Extract<DreamRecord,{kind:'health'}>=>c.kind==='health'&&c.ownerId===user?.id);
 async function task(fn:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');try{await fn();await list.reload();}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 const open=(kind:typeof form)=>{setForm(kind);setTitle('');setNote('');setPlace('');setDay('');setEditId(undefined);};
 return <><PageHeader title="Family & Friends" subtitle="The people and moments that become part of your story."/>{(error||list.error)&&<Notice tone="danger" title={error||list.error!}/>}<div className="mb-5 flex flex-wrap gap-2"><Button onClick={()=>open('person')}>Add a person</Button><Button variant="secondary" onClick={()=>open('gathering')}>Plan a gathering</Button><Button variant="secondary" onClick={()=>open('moment')}>Add a story moment</Button></div>
 {form&&<Card className="mb-5"><form onSubmit={e=>{e.preventDefault();void task(async()=>{if(form==='person')await backend.dreams.save({id:editId,kind:'person',visibility:'shared',payload:{name:title,relationship:relation,note}});else if(form==='gathering')await backend.dreams.save({id:editId,kind:'gathering',visibility:'shared',payload:{title,day,time,place,note}});else await backend.story.add({kind:relation==='Family'?'met_family':'other',title,happenedOn:day||null,body:note||null,remindYearly:false});setForm(null);});}}><h2 className="mb-3 font-bold">{editId?'Edit':form==='person'?'A person in your circle':form==='gathering'?'An upcoming gathering':'A story moment'}</h2><TextField label={form==='person'?'Name':'Title'} value={title} onChange={setTitle} maxLength={160} required/>{form!=='gathering'&&<ChoiceGroup legend="Connection" name="relationship" value={relation} onChange={setRelation} options={['Family','Friend'].map(v=>({value:v,label:v}))}/>} {form!=='person'&&<TextField label="Date" type="date" value={day} onChange={setDay} required={form==='gathering'}/>} {form==='gathering'&&<><TextField label="Time" type="time" value={time} onChange={setTime} required/><TextField label="Place (optional)" value={place} onChange={setPlace}/></>}<TextAreaField label="Notes (shared with your partner)" value={note} onChange={setNote} maxLength={2000}/><p className="my-3 text-sm text-muted">Keep sensitive details about other people out of these shared cards.</p><Button type="submit" loading={busy}>Save shared {form}</Button><Button variant="ghost" onClick={()=>setForm(null)}>Cancel</Button></form></Card>}
 <h2 className="mb-3 text-xl font-bold">Your people</h2><div className="mb-6 grid gap-3 sm:grid-cols-2">{people.map(c=><Card key={c.id}><h3 className="font-bold">{c.payload.name}</h3><p className="text-sm text-muted">{c.payload.relationship}</p><p className="mt-2 whitespace-pre-wrap">{c.payload.note}</p>{c.ownerId===user?.id&&<div className="mt-2"><Button variant="ghost" onClick={()=>{setForm('person');setEditId(c.id);setTitle(c.payload.name);setRelation(c.payload.relationship);setNote(c.payload.note);}}>Edit</Button><Button variant="ghost" disabled={busy} onClick={()=>void task(()=>backend.dreams.remove(c.id))}>Remove</Button></div>}</Card>)}</div>{!people.length&&<p className="mb-5 text-sm text-muted">Add a cousin, a close friend, or someone you are looking forward to meeting.</p>}
 <h2 className="mb-3 text-xl font-bold">Upcoming gatherings</h2><div className="mb-6 space-y-3">{gatherings.filter(c=>c.payload.day>=new Date().toLocaleDateString('en-CA')).map(c=><Card key={c.id}><h3 className="font-bold">{c.payload.title}</h3><p>{c.payload.day} · {c.payload.time} · {c.payload.place}</p><p className="my-2 text-sm">{c.payload.note}</p><Button variant="secondary" onClick={()=>calendar(c)}>Add to my calendar</Button>{c.ownerId===user?.id&&<><Button variant="ghost" onClick={()=>{setForm('gathering');setEditId(c.id);setTitle(c.payload.title);setDay(c.payload.day);setTime(c.payload.time);setPlace(c.payload.place);setNote(c.payload.note);}}>Edit</Button><Button variant="ghost" disabled={busy} onClick={()=>void task(()=>backend.dreams.remove(c.id))}>Remove</Button></>}</Card>)}</div>
 <h2 className="mb-3 text-xl font-bold">Story moments</h2><div className="mb-3 space-y-3">{list.data?.story.filter(s=>s.kind==='met_family'||s.kind==='other').slice(0,5).map(s=><Card key={s.id}><h3 className="font-bold">{s.title}</h3><p className="text-sm text-muted">{s.happenedOn}</p><p>{s.body}</p></Card>)}</div><Link className="mb-6 inline-block font-semibold underline" href="/history/">Open your full relationship history →</Link>
 <Card><h2 className="font-bold">Gentle health reminders</h2><p className="my-2 text-sm text-muted">Optional, private and easy to dismiss. No tracking or streaks.</p><label className="my-3 flex items-start gap-3"><input disabled={busy} type="checkbox" checked={health?.payload.enabled??false} onChange={e=>void task(()=>backend.dreams.save({kind:'health',visibility:'private',payload:{enabled:e.target.checked,dismissed:false}}))}/>Show me a gentle reminder</label>{health?.payload.enabled&&!health.payload.dismissed&&<><p>Would a short walk together or time at the gym feel good this week? Rest counts, too.</p><Button variant="ghost" disabled={busy} onClick={()=>void task(()=>backend.dreams.save({kind:'health',visibility:'private',payload:{enabled:true,dismissed:true}}))}>Dismiss reminder</Button></>}</Card>
 </>;
}
