// @vitest-environment jsdom
import {cleanup,render,screen,fireEvent,waitFor} from '@testing-library/react';
import type {ReactNode} from 'react';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {AppProvider} from '@/components/app-provider';
import {ToastProvider} from '@/components/ui';
import {IntimacyScreen} from '@/components/intimacy/intimacy-screen';
import {PlansScreen,ActivitiesScreen} from '@/components/plans/plans-screen';
import {PeopleScreen} from '@/components/people/people-screen';
import {intimacy} from '@/lib/backend/demo/intimacy';
import {demoStore,DEMO_ALEX,DEMO_SAM} from '@/lib/backend/demo/store';
vi.mock('next/link',()=>({default:({href,children,...rest}:{href:string;children:ReactNode})=><a href={href} {...rest}>{children}</a>}));
vi.mock('next/navigation',()=>({useRouter:()=>({push:vi.fn(),back:vi.fn()}),usePathname:()=>'/intimacy/'}));
const show=(v:ReactNode)=>render(<AppProvider><ToastProvider>{v}</ToastProvider></AppProvider>);
beforeEach(()=>{demoStore.reset(false);demoStore.update(s=>{s.signedIn=true;s.actingAs=DEMO_ALEX;});});afterEach(()=>cleanup());
async function enable(){for(const id of [DEMO_ALEX,DEMO_SAM]){demoStore.update(s=>s.actingAs=id);await intimacy.act({action:'consent',enabled:true,adult:true});await intimacy.act({action:'answer',item:'walk',choice:'yes'});}demoStore.update(s=>s.actingAs=DEMO_ALEX);}
it('requires the age checkbox before local opt-in',async()=>{show(<IntimacyScreen/>);const button=await screen.findByRole('button',{name:'Enable my Intimacy tab'});expect(button.hasAttribute('disabled')).toBe(true);fireEvent.click(screen.getByRole('checkbox',{name:'I confirm I am 18 or older'}));await waitFor(()=>expect(button.hasAttribute('disabled')).toBe(false));});
it('labels fiction, shows only overlaps and repeats Ask first on shared cards',async()=>{await enable();show(<IntimacyScreen/>);expect(await screen.findByText('Demo · fictional Alex and Sam')).toBeTruthy();expect(await screen.findByRole('button',{name:'♡ Spark privately'})).toBeTruthy();expect(screen.queryByRole('heading',{name:'Toys: a conversation first'})).toBeNull();expect(screen.getAllByText('Ask first, and check in as you go.').length).toBeGreaterThanOrEqual(2);});
it('shows safety before play basics every time, with no image URLs',async()=>{await enable();const {container}=show(<IntimacyScreen view="library"/>);const buttons=await screen.findAllByRole('button',{name:'Read safety & basics'});fireEvent.click(buttons[1]!);expect(await screen.findByRole('heading',{name:'Safety comes first'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'I’ve read this · Continue'}));expect(await screen.findByRole('heading',{name:'Boundaries before restraint topics'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Back to library'}));fireEvent.click(screen.getAllByRole('button',{name:'Read safety & basics'})[1]!);expect(await screen.findByRole('heading',{name:'Safety comes first'})).toBeTruthy();expect(container.querySelector('svg image')).toBeNull();});
it('Plans contains choices while the activity log is the last activity action',async()=>{const r=show(<PlansScreen/>);expect(await screen.findByRole('link',{name:/Find an activity idea/})).toBeTruthy();expect(screen.queryByText('Filter activities')).toBeNull();expect(screen.queryByRole('link',{name:'Log an activity'})).toBeNull();r.unmount();const a=show(<ActivitiesScreen/>);await screen.findByRole('heading',{name:'Farmers market + picnic'});const log=screen.getByRole('link',{name:'Log an activity'});expect(a.container.querySelector('a:last-child')).toBeTruthy();expect(log.compareDocumentPosition(screen.getByRole('heading',{name:'Farmers market + picnic'}))&Node.DOCUMENT_POSITION_PRECEDING).toBeTruthy();});
it('Family & Friends stores shared people and keeps health opt-in off',async()=>{show(<PeopleScreen/>);const toggle=await screen.findByRole('checkbox',{name:'Show me a gentle reminder'});expect((toggle as HTMLInputElement).checked).toBe(false);fireEvent.click(screen.getByRole('button',{name:'Add a person'}));fireEvent.change(screen.getByLabelText('Name'),{target:{value:'Cousin Lee'}});fireEvent.click(screen.getByRole('button',{name:'Save shared person'}));expect(await screen.findByRole('heading',{name:'Cousin Lee'})).toBeTruthy();expect(demoStore.get().dreams?.find(c=>c.kind==='person')?.visibility).toBe('shared');});
