import {beforeEach,it,expect,vi,afterEach} from 'vitest';
import {intimacy} from '@/lib/backend/demo/intimacy';
import {demoStore,DEMO_ALEX,DEMO_SAM} from '@/lib/backend/demo/store';
function as(id:string){demoStore.update(s=>{s.signedIn=true;s.actingAs=id;});}
beforeEach(()=>{demoStore.reset(false);as(DEMO_ALEX);});afterEach(()=>vi.useRealTimers());
async function enable(){for(const u of [DEMO_ALEX,DEMO_SAM]){as(u);await intimacy.act({action:'consent',enabled:true,adult:true});await intimacy.act({action:'answer',item:'walk',choice:'yes'});}as(DEMO_ALEX);}
it('keeps two opt-ins independent and maps private',async()=>{await intimacy.act({action:'consent',enabled:true,adult:true});await intimacy.act({action:'answer',item:'walk',choice:'yes'});as(DEMO_SAM);const s=await intimacy.act({action:'list'});expect(s.enabled).toBe(false);expect(s.overlaps).toEqual([]);expect(s.answers).toEqual({});});
it('private sparks, desire and reflection never reach the partner',async()=>{await enable();await intimacy.act({action:'spark',item:'walk'});await intimacy.act({action:'preferences',desire:5,muted:false});await intimacy.saveNote({repeat:'Private wording',change:'Private reflection'});as(DEMO_SAM);const s=await intimacy.act({action:'list'});expect(s.sparks).toEqual([]);expect(s.matched).toEqual([]);expect(s.desire).toBeNull();expect(s.muted).toBe(true);expect((await intimacy.note()).repeat).toBe('');});
it('matches expire after 24h and requires matched sparks to propose time',async()=>{await enable();await expect(intimacy.act({action:'propose',item:'walk',kind:'time',when:new Date(Date.now()+3600000).toISOString()})).rejects.toThrow();for(const u of [DEMO_ALEX,DEMO_SAM]){as(u);await intimacy.act({action:'spark',item:'walk'});}expect((await intimacy.act({action:'list'})).matched).toEqual(['walk']);vi.useFakeTimers();vi.setSystemTime(Date.now()+86400001);expect((await intimacy.act({action:'list'})).matched).toEqual([]);});
it('requires two fresh checks; stepping back ends neutrally',async()=>{await enable();for(const u of [DEMO_ALEX,DEMO_SAM]){as(u);await intimacy.act({action:'spark',item:'walk'});}as(DEMO_ALEX);await intimacy.act({action:'propose',item:'walk',kind:'time',when:new Date(Date.now()+1800000).toISOString()});as(DEMO_SAM);const id=(await intimacy.act({action:'list'})).invitations[0]!.id;await intimacy.act({action:'respond',id,response:'yes'});expect((await intimacy.act({action:'check',id,feeling:true})).invitations[0]!.ready).toBe(false);as(DEMO_ALEX);expect((await intimacy.act({action:'check',id,feeling:true})).invitations[0]!.ready).toBe(true);expect((await intimacy.act({action:'check',id,feeling:false})).invitations[0]!.status).toBe('another_time');});
it('prevents nagging and removes options immediately on a restrictive answer',async()=>{await enable();await intimacy.act({action:'propose',item:'walk',kind:'invite'});as(DEMO_SAM);const id=(await intimacy.act({action:'list'})).invitations[0]!.id;await intimacy.act({action:'respond',id,response:'later'});as(DEMO_ALEX);await expect(intimacy.act({action:'propose',item:'walk',kind:'invite'})).rejects.toThrow();as(DEMO_SAM);await intimacy.act({action:'answer',item:'walk',choice:'not_now'});as(DEMO_ALEX);expect((await intimacy.act({action:'list'})).overlaps).toEqual([]);});
it('does not repeat the same coaching reply immediately',async()=>{await enable();const one=await intimacy.coach('build anticipation',false),two=await intimacy.coach('build anticipation',false);expect(one.reply).not.toBe(two.reply);});
