// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen,waitFor,act} from '@testing-library/react';
import type {ReactNode} from 'react';
import {AppProvider} from '@/components/app-provider';
import {ToastProvider} from '@/components/ui';
import {CoachingWelcome} from '@/components/dreams/coaching-welcome';
import {DreamsScreen} from '@/components/dreams/dreams-screen';
import {demoStore,DEMO_ALEX,DEMO_SAM} from '@/lib/backend/demo/store';
import {createDemoBackend} from '@/lib/backend/demo';
vi.mock('next/link',()=>({default:({href,children,...rest}:{href:string;children:ReactNode})=><a href={href} {...rest}>{children}</a>}));
vi.mock('next/navigation',()=>({useRouter:()=>({push:vi.fn(),replace:vi.fn(),back:vi.fn()}),usePathname:()=>'/plans/dreams/',useSearchParams:()=>new URLSearchParams()}));
const b=createDemoBackend();const show=(view:Parameters<typeof DreamsScreen>[0]['view'])=>render(<AppProvider><ToastProvider><DreamsScreen view={view}/></ToastProvider></AppProvider>);
beforeEach(()=>{localStorage.clear();sessionStorage.clear();demoStore.reset(false);b.demo!.actAs(DEMO_ALEX);});afterEach(cleanup);
it('creates a private dream and hides it after switching partners',async()=>{show('board');fireEvent.click(await screen.findByRole('button',{name:'Add dream'}));fireEvent.change(screen.getByLabelText('My dream'),{target:{value:'My private cabin'}});expect((screen.getByLabelText('Share this entire dream card with my partner') as HTMLInputElement).checked).toBe(false);fireEvent.click(screen.getByRole('button',{name:'Save privately'}));await screen.findByRole('heading',{name:'My private cabin'});act(()=>b.demo!.actAs(DEMO_SAM));await waitFor(()=>expect(screen.queryByRole('heading',{name:'My private cabin'})).toBeNull());});
it('offers a mirror before publishing a complaint draft',async()=>{show('week');fireEvent.click(await screen.findByRole('button',{name:'Add support request'}));fireEvent.change(screen.getByLabelText('What I need this week'),{target:{value:'You never listen'}});expect(screen.getByText('A pause before sharing')).toBeTruthy();expect((screen.getByRole('button',{name:'Save and share'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.change(screen.getByLabelText('What I need this week'),{target:{value:'I would appreciate time together'}});fireEvent.click(screen.getByRole('button',{name:'Save and share'}));await screen.findByRole('heading',{name:'I would appreciate time together'});});
it('saves private Life Anchors and a changeable coaching style',async()=>{show('anchors');fireEvent.click(await screen.findByRole('button',{name:'Add life anchors'}));fireEvent.change(screen.getByLabelText('My coaching style'),{target:{value:'driven'}});fireEvent.change(screen.getByLabelText('A hobby that matters to me'),{target:{value:'Gaming'}});fireEvent.click(screen.getByRole('button',{name:'Save privately'}));await screen.findByText('Gaming');expect((await b.dreams.list()).items.find(x=>x.kind==='anchors')?.payload).toMatchObject({track:'driven',hobby:'Gaming'});});
it('waits for both roadmap choices and exposes no create button while closed',async()=>{show('roadmap');const add=await screen.findByRole('button',{name:'Add roadmap'});expect((add as HTMLButtonElement).disabled).toBe(true);fireEvent.click(screen.getByRole('button',{name:'Join the shared roadmap'}));await screen.findByRole('button',{name:'Leave the shared roadmap'});expect((screen.getByRole('button',{name:'Add roadmap'}) as HTMLButtonElement).disabled).toBe(true);});
it('shows a twenty-minute conversation with no score for the partner',async()=>{show('review');await screen.findByRole('heading',{name:'Twenty minutes, together'});expect(screen.getByText('One ask each')).toBeTruthy();expect(screen.getByText(/No streaks, partner scores/)).toBeTruthy();});

it('offers a private coaching choice on the first paired visit, then stops prompting',async()=>{render(<AppProvider><ToastProvider><CoachingWelcome/></ToastProvider></AppProvider>);fireEvent.click(await screen.findByRole('button',{name:'Warm'}));await waitFor(()=>expect(screen.queryByRole('heading',{name:'How should Buddy support you?'})).toBeNull());expect((await b.dreams.list()).items.find(x=>x.kind==='anchors')?.payload).toMatchObject({track:'warm'});});
